logicalclocks/terraform-provider-hopsworksai

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go
Closes https://github.com/logicalclocks/hopsworks-cloud/issues/2063
=> [HOPSWORKS-CLOUD-2063] add support for init script

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, hopsworksai/internal/api/model.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go
Closes https://github.com/logicalclocks/hopsworks-cloud/issues/2109
=> [HOPSWORKS-CLOUD-2109] add support for centos

examples/complete/azure/aks/README.md
=> fix aks example readme

CHANGELOG.md, DEVELOPMENT.md, test-fixtures/aws/main.tf, test-fixtures/aws/outputs.tf, test-fixtures/aws/variables.tf, test-fixtures/main.tf, test-fixtures/run-acceptance-tests.sh, test-fixtures/variables.tf
Closes https://github.com/logicalclocks/hopsworks-cloud/issues/2120
=> Add support for setting profile on aws during acceptance tests

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
=> [TERRAFORM-PROVIDER-23] let user set search domain in azure

CHANGELOG.md
=> release 0.5

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, hopsworksai/internal/api/apis.go, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/27
=> Add support for upgrades

hopsworksai/resource_cluster_from_backup_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/39
=> Ensure that testing envvars do not collide when running AWS and AZURE tests

CHANGELOG.md, examples/complete/aws/autoscale/main.tf, examples/complete/aws/autoscale/variables.tf, examples/complete/aws/eks/main.tf, examples/complete/aws/eks/variables.tf
Fixes #62 
We can't really make tests for examples so no tests were added.
=> [terraform-provider-hopsworksai-62] add aws profile in examples

CHANGELOG.md, hopsworksai/resource_cluster.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/74
=> Fix interface conversion issue in cluster resource

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/76
=> Update default version to 2.5.0

CHANGELOG.md, hopsworksai/data_source_aws_instance_profile_policy.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/85
=> Add missing backup permissions on aws_instance_profile

CHANGELOG.md, hopsworksai/internal/api/model.go, hopsworksai/internal/test/resource.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/70
=> Adapt upgrade to work for clusters 2.4.0 and onwards

CHANGELOG.md, hopsworksai/internal/api/apis.go, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go, test-fixtures/main.tf
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/80
=> Add support for upscaling head node and RonDB nodes

CHANGELOG.md, hopsworksai/data_source_backup_test.go, hopsworksai/data_source_backups_test.go, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster_from_backup_test.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/106
=> Tag acceptance tests resources with their respective test name

CHANGELOG.md, hopsworksai/data_source_aws_instance_profile_policy_test.go, hopsworksai/data_source_azure_user_assigned_identity_permissions_test.go, hopsworksai/data_source_backup_test.go, hopsworksai/data_source_backups_test.go, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/data_source_instance_types_test.go, hopsworksai/provider_test.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster_from_backup_test.go, hopsworksai/resource_cluster_test.go, test-fixtures/run-acceptance-tests.sh
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/108
=> [Acceptance Tests] Providers is deprecated use ProviderFactories instead

hopsworksai/hopsworksai_sweeper_test.go, hopsworksai/provider_test.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/112
Caused by https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/108
=> Create api client instead of using the providers meta object

CHANGELOG.md, go.mod, hopsworksai/internal/api/api_client.go, hopsworksai/internal/api/apis.go, hopsworksai/resource_backup.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/100
=> Use tflog instead of log package for logging

CHANGELOG.md, README.md, docs/index.md, examples/complete/aws/autoscale/versions.tf, examples/complete/aws/basic/versions.tf, examples/complete/aws/eks/versions.tf, examples/complete/aws/rondb/versions.tf, examples/complete/azure/aks/versions.tf, examples/complete/azure/autoscale/versions.tf, examples/complete/azure/basic/versions.tf, examples/complete/azure/rondb/versions.tf, examples/provider/provider_aws.tf, examples/provider/provider_azure.tf
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/121
=> Pin provider versions to avoid breaking changes

CHANGELOG.md, hopsworksai/internal/api/model.go, hopsworksai/resource_backup.go, hopsworksai/resource_backup_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/126
=> Handle get backup if backup not found and backupPipeline is InProgress

CHANGELOG.md, hopsworksai/resource_backup.go, hopsworksai/resource_backup_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/129
=> Wait for cluster start during backup pipeline

CHANGELOG.md, hopsworksai/resource_backup.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/131
=> Fix interface conversion error

CHANGELOG.md, hopsworksai/resource_backup.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/133
=> Return empty backup object when pending to avoid not found checks

CHANGELOG.md, docs/index.md, go.mod, hopsworksai/internal/api/api_client.go, hopsworksai/provider.go, hopsworksai/provider_test.go
=> [tf-125] Provider configuration option to specify the API Gateway

hopsworksai/hopsworksai_sweeper_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/125
=> Add default apit gateway for test sweepers

.github/workflows/golint.yml, CHANGELOG.md, README.md
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/139
=> Bump golangci-lint version to 1.45.2

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, examples/complete/aws/basic/main.tf, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/162
=> Add support for EBS encryption

CHANGELOG.md, README.md, docs/data-sources/instance_type.md, docs/data-sources/instance_types.md, docs/index.md, examples/complete/aws/autoscale/main.tf, examples/complete/aws/basic/main.tf, examples/complete/aws/eks/main.tf, examples/complete/azure/aks/main.tf, examples/complete/azure/autoscale/main.tf, examples/complete/azure/basic/main.tf, examples/data-sources/hopsworksai_instance_type/data-source.tf, examples/data-sources/hopsworksai_instance_types/data-source.tf, examples/provider/provider_aws.tf, examples/provider/provider_azure.tf, hopsworksai/data_source_instance_type.go, hopsworksai/data_source_instance_types.go, hopsworksai/internal/api/apis.go, hopsworksai/internal/api/apis_test.go
- [] Passes the tests including acceptance test
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/173
=> Filter supported instance types based on region

CHANGELOG.md, docs/data-sources/cluster.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, hopsworksai/resource_cluster.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/168
=> Document supported values for update_state attribute

hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster_test.go
=> Fix acceptance tests

CHANGELOG.md, docs/data-sources/aws_instance_profile_policy.md, docs/data-sources/azure_user_assigned_identity_permissions.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, hopsworksai/data_source_aws_instance_profile_policy.go, hopsworksai/data_source_aws_instance_profile_policy_test.go, hopsworksai/data_source_azure_user_assigned_identity_permissions.go, hopsworksai/data_source_azure_user_assigned_identity_permissions_test.go, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/provider_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go, test-fixtures/aws/main.tf, test-fixtures/azure/main.tf
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/149
=> Preparing for 1.0.0 release

hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/185
=> Fix default RonDB instance types for Azure

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/189
=> Set default version to 3.0.0

CHANGELOG.md, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster_from_backup_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/191
=> Update acceptance tests for backups

CHANGELOG.md, hopsworksai/data_source_azure_user_assigned_identity_permissions.go, hopsworksai/data_source_azure_user_assigned_identity_permissions_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/194
=> Add the missing listkeys action permissions for backup

hopsworksai/data_source_backup_test.go, hopsworksai/data_source_backups_test.go, hopsworksai/resource_cluster_from_backup_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/191
=> Update acceptance tests for backups - append

CHANGELOG.md, README.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/index.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, examples/provider/provider_aws.tf, examples/provider/provider_azure.tf, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/api/model_test.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://github.com/logicalclocks/terraform-provider-hopsworksai/issues/196
=> Add rondb/single_node block to define RonDB all-in-one

docs/data-sources/backup.md, examples/data-sources/hopsworksai_backup/data-source.tf, examples/resources/hopsworksai_cluster_from_backup/resource.tf
Closes https://hopsworks.atlassian.net/browse/CLOUD-73
Relates #0000
=> [CLOUD-73] fix typo in backup restore

CHANGELOG.md
=> Update changelog after release v1.1.0

hopsworksai/resource_cluster.go
https://hopsworks.atlassian.net/browse/CLOUD-120
=> [CLOUD-120] append - set Computed true for backward compatiblity

CHANGELOG.md, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
https://hopsworks.atlassian.net/browse/CLOUD-96
=> [CLOUD-96] Use managed docker registry by default

CHANGELOG.md, docs/data-sources/instance_type.md, docs/data-sources/instance_types.md, hopsworksai/data_source_instance_type.go, hopsworksai/data_source_instance_type_test.go, hopsworksai/data_source_instance_types.go, hopsworksai/data_source_instance_types_test.go, hopsworksai/internal/api/api_client.go, hopsworksai/internal/api/model.go, hopsworksai/internal/api/test/http_client_fixture.go, hopsworksai/internal/structure/supported_instance_types.go, hopsworksai/internal/structure/supported_instance_types_test.go, hopsworksai/internal/test/resource.go
Fixes https://hopsworks.atlassian.net/browse/CLOUD-139
=> [CLOUD-139] filter instance types based on nvme

CHANGELOG.md, acceptance-test.jenkins, test-fixtures/run-acceptance-tests.sh
Fixes https://hopsworks.atlassian.net/browse/CLOUD-183
=> [CLOUD-183] make a jenkins pipeline for integration tests

CHANGELOG.md, hopsworksai/resource_cluster_test.go
Fixes https://hopsworks.atlassian.net/browse/CLOUD-192
=> [CLOUD-195] fix TestAccClusterAWS_RonDB and TestAccClusterAzure_RonDB

CHANGELOG.md, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster_test.go
Fixes https://hopsworks.atlassian.net/browse/CLOUD-204
=> [CLOUD-204] collect ec2init log in aws acceptance tests

CHANGELOG.md, hopsworksai/data_source_aws_instance_profile_policy.go, hopsworksai/data_source_aws_instance_profile_policy_test.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-28
=> [CLOUD-28] Add permissions for service images

CHANGELOG.md, docs/data-sources/aws_instance_profile_policy.md, docs/data-sources/azure_user_assigned_identity_permissions.md, hopsworksai/data_source_aws_instance_profile_policy.go, hopsworksai/data_source_aws_instance_profile_policy_test.go, hopsworksai/data_source_azure_user_assigned_identity_permissions.go, hopsworksai/data_source_azure_user_assigned_identity_permissions_test.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-145
=> [CLOUD-145] Seperate AKS/EKS permissions from ACR/ECR

CHANGELOG.md, GNUmakefile, acceptance-test.jenkins, docs/data-sources/aws_instance_profile_policy.md, docs/index.md, docs/resources/cluster.md, examples/complete/azure/autoscale/main.tf, examples/complete/azure/basic/main.tf, examples/data-sources/hopsworksai_aws_instance_profile_policy/data-source.tf, examples/provider/provider_azure.tf, examples/resources/hopsworksai_cluster/resource_azure.tf, hopsworksai/data_source_cluster_test.go, hopsworksai/data_source_clusters_test.go, hopsworksai/provider_test.go, hopsworksai/resource_backup_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go, test-fixtures/aws/main.tf, test-fixtures/azure/main.tf, test-fixtures/azure/outputs.tf, test-fixtures/azure/variables.tf, test-fixtures/cleanup-acceptance-tests.sh, test-fixtures/main.tf, test-fixtures/outputs.tf, test-fixtures/run-acceptance-tests.sh
Closes https://hopsworks.atlassian.net/browse/CLOUD-144
=> [CLOUD-144] Update acceptance tests and examples for new release

CHANGELOG.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-259
[CLOUD-259]: https://hopsworks.atlassian.net/browse/CLOUD-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLOUD-259] release version 1.3.0

CHANGELOG.md, DEVELOPMENT.md
Fixes https://hopsworks.atlassian.net/browse/CLOUD-260
[CLOUD-260]: https://hopsworks.atlassian.net/browse/CLOUD-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLOUD-260] make 1.3.1 the working version

CHANGELOG.md, hopsworksai/internal/api/apis.go, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-83
=> [CLOUD-83] Fixes for upgrade from 3.0 to 3.1

acceptance-test.jenkins
Fixes https://hopsworks.atlassian.net/browse/CLOUD-327
=> [CLOUD-327] remove support for ap-south-1, eu-central-1 and us-west-1

CHANGELOG.md, docs/data-sources/aws_instance_profile_policy.md, hopsworksai/data_source_aws_instance_profile_policy.go, hopsworksai/data_source_aws_instance_profile_policy_test.go
Fixes https://hopsworks.atlassian.net/browse/CLOUD-360
=> [CLOUD-360] limit ecr to region and account

CHANGELOG.md, hopsworksai/data_source_aws_instance_profile_policy.go
Fixes https://hopsworks.atlassian.net/browse/CLOUD-396
=> [CLOUD-396] remove unused permission from asw instance profile policy

CHANGELOG.md, README.md, examples/complete/aws/autoscale/main.tf, examples/complete/aws/basic/main.tf, examples/complete/aws/eks/main.tf, examples/complete/azure/aks/main.tf, examples/complete/azure/autoscale/main.tf, examples/complete/azure/basic/main.tf, examples/provider/provider_aws.tf, examples/provider/provider_azure.tf
Closes https://hopsworks.atlassian.net/browse/CLOUD-480
=> [CLOUD-480] Update terraform helpers modules

README.md, docs/index.md, examples/complete/aws/autoscale/main.tf, examples/complete/aws/basic/main.tf, examples/complete/aws/eks/main.tf, examples/complete/azure/aks/main.tf, examples/complete/azure/autoscale/main.tf, examples/complete/azure/basic/main.tf, examples/provider/provider_azure.tf
Closes https://hopsworks.atlassian.net/browse/CLOUD-480
=> [CLOUD-480] append - remove deprecated attributes

CHANGELOG.md, examples/complete/azure/README.md, examples/complete/azure/advanced/README.md, examples/complete/azure/advanced/aks-with-peering/README.md, examples/complete/azure/advanced/aks-with-peering/aks.tf, examples/complete/azure/advanced/aks-with-peering/hopsworks.tf, examples/complete/azure/advanced/aks-with-peering/main.tf, examples/complete/azure/advanced/aks-with-peering/outputs.tf, examples/complete/azure/advanced/aks-with-peering/variables.tf, examples/complete/azure/advanced/aks-with-peering/versions.tf
Closes https://hopsworks.atlassian.net/browse/CLOUD-485
=> [CLOUD-485] Add advanced azure aks example

CHANGELOG.md, hopsworksai/data_source_aws_instance_profile_policy.go, hopsworksai/data_source_aws_instance_profile_policy_test.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-412
=> [CLOUD-412] Add testconnector to the cloud

CHANGELOG.md, README.md, docs/index.md, examples/complete/aws/autoscale/main.tf, examples/complete/aws/basic/main.tf, examples/complete/aws/eks/main.tf, examples/complete/azure/aks/main.tf, examples/complete/azure/autoscale/main.tf, examples/complete/azure/basic/main.tf, examples/provider/provider_aws.tf, examples/provider/provider_azure.tf
Closes https://hopsworks.atlassian.net/browse/CLOUD-538
=> [CLOUD-538] Update helpers module version

CHANGELOG.md, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-534
=> [CLOUD-534] Check version should handle cases with version suffix is present

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-541
=> [CLOUD-541] Release 3.2.0

CHANGELOG.md, test-fixtures/aws/main.tf
Closes https://hopsworks.atlassian.net/browse/CLOUD-609
=> [CLOUD-609] Acceptance tests to run against dev and prod

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-634
=> [CLOUD-634] Release 3.3.0

CHANGELOG.md
=> Release version 1.7.0

CHANGELOG.md
=> [dev_1.8.0] Prepare development for 1.8.0

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, hopsworksai/data_source_aws_instance_profile_policy.go, hopsworksai/data_source_aws_instance_profile_policy_test.go, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-636
=> [CLOUD-636] Add support for ArrowFlight server with DuckDB

examples/complete/aws/eks/main.tf
=> Update default eks version in the example to 1.26

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-652
=> [CLOUD-652] Set default version to 3.4.0

CHANGELOG.md, docs/data-sources/cluster.md, docs/data-sources/clusters.md, docs/data-sources/instance_type.md, docs/data-sources/instance_types.md, docs/resources/cluster.md, docs/resources/cluster_from_backup.md, examples/complete/aws/autoscale/README.md, examples/complete/aws/basic/README.md, examples/complete/azure/autoscale/README.md, examples/complete/azure/basic/README.md, hopsworksai/data_source_instance_type.go, hopsworksai/data_source_instance_type_test.go, hopsworksai/data_source_instance_types.go, hopsworksai/data_source_instance_types_test.go, hopsworksai/internal/api/apis_test.go, hopsworksai/internal/api/model.go, hopsworksai/internal/api/model_test.go, hopsworksai/internal/structure/cluster.go, hopsworksai/internal/structure/cluster_test.go, hopsworksai/internal/structure/supported_instance_types.go, hopsworksai/internal/structure/supported_instance_types_test.go, hopsworksai/resource_cluster.go, hopsworksai/resource_cluster_test.go
=> [CLOUD-576] Drop support for GPU worker nodes in the cloud

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-663
=> [CLOUD-663] Update version from 3.4.0 to 3.4.1

.github/workflows/unit-test.yml
Reverts logicalclocks/terraform-provider-hopsworksai#279
=> Revert "Bump codecov/codecov-action from 3 to 4"

CHANGELOG.md, docs/resources/cluster.md, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-685
=> [CLOUD-685] Set default version to 3.5.0

CHANGELOG.md, docs/resources/cluster.md, examples/complete/gcp/gke/standard/main.tf, hopsworksai/resource_cluster.go
Closes https://hopsworks.atlassian.net/browse/CLOUD-722
=> [CLOUD-722] Set default version to 3.7.1

CHANGELOG.md
=> Release 1.12.0

CHANGELOG.md
=> Prepare development for 1.12.1
